import { MonthWiseTransitPrediction, GrahaName } from './types';

export const ALL_MONTH_WISE_PREDICTIONS: MonthWiseTransitPrediction[] = [
  // ==========================================
  // YEAR 2025 (JULY TO DECEMBER)
  // ==========================================
  {
    monthKey: '2025-07',
    monthName: 'July 2025',
    tagline: 'Guru Purnima Divine Auspice & Solar Ingress into Karka',
    overallRating: 4,
    planetaryMovements: [
      { planet: 'Surya' as GrahaName, event: 'Surya enters Karka (Cancer) on Jul 16 (Karka Sankranti)', date: 'Jul 16, 2025', impactSummary: 'Deepens emotional sensitivity, domestic focus, and maternal bonding.' },
      { planet: 'Guru' as GrahaName, event: 'Guru transits Mithuna (Gemini)', date: 'All Month', impactSummary: 'Fosters intellectual expansion, media ventures, and commercial networking.' },
      { planet: 'Shani' as GrahaName, event: 'Shani stations retrograde in Meena (Pisces)', date: 'Jul 13, 2025', impactSummary: 'Commences inward karmic review of subconscious commitments and boundary management.' },
    ],
    careerWealthForecast: 'Excellent for strategic planning, documentation reviews, and creative marketing campaigns. Post-Sankranti favors real estate and domestic asset investments.',
    loveFamilyForecast: 'Guru Purnima fosters profound reverence for mentors and elders. Marital bonds deepen through sincere emotional care and home dinners.',
    healthVitalityForecast: 'Pay attention to chest, lungs, and water retention during the monsoon shift. Drink warm ginger water and maintain regular sleep hours.',
    spiritualForecast: 'Guru Purnima (Ashadha Purnima): Ideal for seeking Guru diksha, chanting Gayatri mantra, and honoring lineage teachers.',
    dos: [
      'Seek the blessings of your spiritual preceptor or parents on Guru Purnima.',
      'Audit monthly expenditure and initiate emergency liquid savings.',
      'Incorporate herbal basil (Tulsi) tea and practice Anulom-Vilom Pranayama.',
    ],
    donts: [
      'Avoid emotional impulsiveness in business partnerships.',
      'Do not neglect domestic responsibilities under workplace ambition.',
    ],
    favorableDays: 'Jul 4, 10, 15, 21, 26, 30',
    cautionDays: 'Jul 8, 16 (Karka Sankranti), 24 (Moon in 8th house)',
    remedyOfMonth: 'Offer yellow flowers and gram pulse (chana dal) at a Vishnu or Shiva shrine on Thursdays.',
  },
  {
    monthKey: '2025-08',
    monthName: 'August 2025',
    tagline: 'Surya in Own Swakshetra Simha & Krishna Janmashtami Grace',
    overallRating: 5,
    planetaryMovements: [
      { planet: 'Surya' as GrahaName, event: 'Surya enters own royal sign Simha (Leo) on Aug 17', date: 'Aug 17, 2025', impactSummary: 'Magnificent surge in authority, executive decision-making, and public leadership.' },
      { planet: 'Mangal' as GrahaName, event: 'Mangal transit through Kanya activates analytical vigor', date: 'Aug 11-31', impactSummary: 'Sharpens problem-solving, technical troubleshooting, and competitor defense.' },
      { planet: 'Shukra' as GrahaName, event: 'Shukra transits Karka and Simha', date: 'All Month', impactSummary: 'Elevates festive warmth, jewelry purchases, and theatrical/creative aesthetics.' },
    ],
    careerWealthForecast: 'Peak period for governmental contracts, leadership promotions, and corporate negotiations. High return on bold, well-researched initiatives.',
    loveFamilyForecast: 'Raksha Bandhan strengthens sibling bonds. Janmashtami brings joyful spiritual family celebrations and festive harmony.',
    healthVitalityForecast: 'Strong cardiovascular vitality and metabolic Agni. Guard against bile (Pitta) excess by avoiding overly spicy and oily fried food.',
    spiritualForecast: 'Krishna Janmashtami: Fasting until midnight and chanting the Gopala mantra dispels lingering past karmic debts.',
    dos: [
      'Recite the Aditya Hridaya Stotra at sunrise facing East.',
      'Celebrate Rakhi and Krishna Janmashtami with family harmony and charity.',
      'Step up to take command of stagnant workplace projects.',
    ],
    donts: [
      'Avoid authoritarian arrogance or dismissal of junior feedback.',
      'Do not overindulge in heavy sweets during late-night festivals.',
    ],
    favorableDays: 'Aug 3, 9, 14, 19, 24, 29',
    cautionDays: 'Aug 6, 17 (Simha Sankranti), 27',
    remedyOfMonth: 'Offer fresh water with red kumkum and flower petals to Lord Surya at dawn every Sunday.',
  },
  {
    monthKey: '2025-09',
    monthName: 'September 2025',
    tagline: 'Pitru Paksha Ancestral Grace & Exalted Budha in Kanya',
    overallRating: 4,
    planetaryMovements: [
      { planet: 'Budha' as GrahaName, event: 'Budha enters exalted sign Kanya (Virgo) forming Bhadra Yoga', date: 'Sep 12, 2025', impactSummary: 'Exceptional intellectual brilliance, mathematical acuity, and commercial prowess.' },
      { planet: 'Surya' as GrahaName, event: 'Surya enters Kanya (Virgo) on Sep 17', date: 'Sep 17, 2025', impactSummary: 'Focus shifts toward organizational efficiency, service, and detail audits.' },
      { planet: 'Shani' as GrahaName, event: 'Shani retrograde in Meena directly opposes Kanya planets', date: 'All Month', impactSummary: 'Demands patience in executing detailed structural overhauls.' },
    ],
    careerWealthForecast: 'Unmatched clarity for accounting audits, software code releases, and contractual renegotiations. Favorable for intellectual consulting.',
    loveFamilyForecast: 'Clear, honest communication heals long-standing misunderstandings. Ancestral remembrance brings peace to family elders.',
    healthVitalityForecast: 'Focus on intestinal health, gut microbiome, and digestive enzymes. Incorporate light khichdi and cumin-coriander herbal water.',
    spiritualForecast: 'Pitru Paksha: Dedicate 16 days to Tarpan, Pinda Daan, and feeding cows, crows, and underprivileged persons for Pitru Dosha relief.',
    dos: [
      'Perform Tarpan or charitable donations in honor of ancestors.',
      'Organize accounting books, tax declarations, and legal wills.',
      'Leverage exalted Mercury for data analysis, writing, and strategic study.',
    ],
    donts: [
      'Avoid hypercritical nitpicking with domestic help or colleagues.',
      'Refrain from starting ostentatious luxury celebrations during Shradha Paksha.',
    ],
    favorableDays: 'Sep 2, 7, 13, 18, 23, 28',
    cautionDays: 'Sep 5, 17 (Kanya Sankranti), 25 (Mahalaya Amavasya)',
    remedyOfMonth: 'Feed green grass or spinach to cows on Wednesdays and donate black sesame seeds on Saturdays.',
  },
  {
    monthKey: '2025-10',
    monthName: 'October 2025',
    tagline: 'Sharad Navratri Divine Shakti & Vijayadashami Triumph',
    overallRating: 5,
    planetaryMovements: [
      { planet: 'Surya' as GrahaName, event: 'Surya enters Tula (Debilitated sign) on Oct 17', date: 'Oct 17, 2025', impactSummary: 'Demands humility, diplomacy, and balancing ego against collective consensus.' },
      { planet: 'Shukra' as GrahaName, event: 'Shukra transits Tula (own sign) creating Malavya Yoga', date: 'Oct 1-24', impactSummary: 'Magnificent artistic charm, diplomatic success, romantic glamour, and luxury acquisitions.' },
      { planet: 'Mangal' as GrahaName, event: 'Mangal enters Tula joining Shukra & Surya', date: 'Late October', impactSummary: 'Generates intense creative passion and enterprise drive, with need to manage temper.' },
    ],
    careerWealthForecast: 'High commercial revenue through consumer goods, fashion, jewelry, and creative arts. Partnership ventures prosper with transparent written terms.',
    loveFamilyForecast: 'Sublime romantic bliss and festive joy during Sharad Navratri, Dussehra, and Karwa Chauth. Marital intimacy and social popularity reach peak levels.',
    healthVitalityForecast: 'Maintain kidney and urinary wellness through abundant pure water intake. Avoid excessive festive sugar consumption.',
    spiritualForecast: 'Sharad Navratri: Invoke Goddess Durga with daily recitation of Devi Kavacham and Durga Saptashati for protection and divine radiance.',
    dos: [
      'Observe Navratri fasts with devotion and light an Akhand Jyot.',
      'Initiate new ethical business partnerships on Vijayadashami (Dussehra).',
      'Harmonize marital relations through affectionate respect and gifts.',
    ],
    donts: [
      'Avoid aggressive confrontation with legal or governmental authorities after Oct 17.',
      'Do not let pride eclipse diplomatic tact in negotiations.',
    ],
    favorableDays: 'Oct 3, 9, 14, 20, 25, 30',
    cautionDays: 'Oct 7, 17 (Tula Sankranti), 28',
    remedyOfMonth: 'Recite Argala Stotra daily and donate white sweets or rice to young girls (Kanya Pujan).',
  },
  {
    monthKey: '2025-11',
    monthName: 'November 2025',
    tagline: 'Diwali Deepavali Prosperity & Mystical Scorpionic Depths',
    overallRating: 5,
    planetaryMovements: [
      { planet: 'Surya' as GrahaName, event: 'Surya enters Vrischika (Scorpio) on Nov 16', date: 'Nov 16, 2025', impactSummary: 'Ignites deep research intuition, esoteric curiosity, and investigative stamina.' },
      { planet: 'Guru' as GrahaName, event: 'Guru retrogrades in Mithuna', date: 'Nov 11-30', impactSummary: 'Internalizes wisdom, prompting philosophical re-evaluation of long-term aspirations.' },
      { planet: 'Shukra' as GrahaName, event: 'Shukra in Vrischika activates passionate intimacy', date: 'All Month', impactSummary: 'Deep emotional bonding, shared investment discussions, and festive elegance.' },
    ],
    careerWealthForecast: 'Phenomenal for festival trade, strategic asset reallocation, and clearing long-pending debts. Dhanteras and Diwali open auspicious revenue streams.',
    loveFamilyForecast: 'Festive warmth and joyful reunions during Diwali, Govardhan Puja, and Bhai Dooj. Deep emotional vulnerability and bonding with spouse.',
    healthVitalityForecast: 'Protect reproductive and excretory health. Practice warming Ayurvedic sesame oil massage (Abhyanga) before morning baths.',
    spiritualForecast: 'Diwali Lakshmi-Kuber Puja: Auspicious Maharatri for invoking financial stability, inner light, and spiritual liberation.',
    dos: [
      'Perform traditional Lakshmi-Ganesha Puja during evening Pradosh Kaal on Diwali.',
      'Clear outstanding debts and make generous donations to the needy.',
      'Deep-clean and illuminate all dark corners of your living space.',
    ],
    donts: [
      'Avoid gambling or risky speculative betting on Diwali night.',
      'Do not harbor bitterness or jealousy during family festivities.',
    ],
    favorableDays: 'Nov 2, 8, 12, 18, 23, 28',
    cautionDays: 'Nov 6, 16 (Vrischika Sankranti), 26',
    remedyOfMonth: 'Light 11 clay ghee lamps at home and chant Om Shreem Mahalakshmiyei Namah 108 times.',
  },
  {
    monthKey: '2025-12',
    monthName: 'December 2025',
    tagline: 'Gita Jayanti Wisdom & Year-End Dharmic Realignment',
    overallRating: 4,
    planetaryMovements: [
      { planet: 'Surya' as GrahaName, event: 'Surya enters Dhanu (Sagittarius) on Dec 16', date: 'Dec 16, 2025', impactSummary: 'Activates philosophical inquiry, higher education, long-range vision, and pilgrimage.' },
      { planet: 'Shani' as GrahaName, event: 'Shani resumes direct motion in Meena', date: 'Early Dec', impactSummary: 'Unlocks forward progress on delayed long-term construction, career, and karmic initiatives.' },
    ],
    careerWealthForecast: 'Consolidate annual achievements and formulate disciplined 2026 strategic objectives. Favorable for international business and publication.',
    loveFamilyForecast: 'High-minded, philosophical discussions with family. Winter holidays and spiritual travels bring mutual bonding.',
    healthVitalityForecast: 'Guard thighs, liver, and hips. Avoid excessive rich holiday foods and drink warm cinnamon-clove spiced herbal tea.',
    spiritualForecast: 'Gita Jayanti and Mokshada Ekadashi: Supreme day for reading Bhagavad Gita Chapter 12 and 15 for liberation.',
    dos: [
      'Read from the Bhagavad Gita and meditate on righteous action (Karma Yoga).',
      'Donate warm woolen clothes and blankets to underprivileged people on chilly Saturdays.',
      'Conduct a thorough year-end financial audit and express gratitude for blessings.',
    ],
    donts: [
      'Avoid overpromising on project deliverables during holiday closures.',
      'Do not neglect morning meditation due to winter lethargy.',
    ],
    favorableDays: 'Dec 4, 9, 15, 20, 25, 30',
    cautionDays: 'Dec 7, 16 (Dhanu Sankranti), 27',
    remedyOfMonth: 'Chant Vishnu Sahasranama on Thursdays and feed birds with soaked grains.',
  },

  // ==========================================
  // YEAR 2026 (FULL 12 MONTHS)
  // ==========================================
  {
    monthKey: '2026-01',
    monthName: 'January 2026',
    tagline: 'Makara Sankranti / Uttarayan Divine Solar Rebirth',
    overallRating: 5,
    planetaryMovements: [
      { planet: 'Surya' as GrahaName, event: 'Surya enters Makara (Capricorn) on Jan 14 (Makara Sankranti)', date: 'Jan 14, 2026', impactSummary: 'Commences Uttarayan: Northern solar movement infusing vitality, discipline, and success.' },
      { planet: 'Mangal' as GrahaName, event: 'Mangal transit in exalted/angular strength', date: 'All Month', impactSummary: 'Unstoppable willpower, athletic vigor, and high enterprise momentum.' },
    ],
    careerWealthForecast: 'Prime period for launching ambitious annual projects, taking executive leadership roles, and closing long-pending land or property transactions.',
    loveFamilyForecast: 'Steady, grounded family dynamics. Shared responsibilities and mutual respect create deep domestic stability.',
    healthVitalityForecast: 'High physical stamina and endurance. Excellent time to begin a strict daily fitness and yoga regimen.',
    spiritualForecast: 'Makara Sankranti: Sacred river bath, Surya Gayatri chanting, and charity of sesame and jaggery bring radiant health.',
    dos: [
      'Celebrate Makara Sankranti by donating Til-Gud, blankets, and khichdi.',
      'Set ambitious 2026 professional milestones and establish daily accountability.',
      'Rise early during Brahma Muhurta to harness rising solar prana.',
    ],
    donts: [
      'Avoid harsh speech or tyrannical micro-management at work.',
      'Do not neglect family warmth in pursuit of relentless career goals.',
    ],
    favorableDays: 'Jan 3, 9, 14, 19, 25, 31',
    cautionDays: 'Jan 7, 14 (Sankranti day), 23',
    remedyOfMonth: 'Recite Aditya Hridaya Stotra at sunrise every Sunday facing East.',
  },
  {
    monthKey: '2026-02',
    monthName: 'February 2026',
    tagline: 'Maha Shivratri Transcendence & Aquarius Social Innovations',
    overallRating: 4,
    planetaryMovements: [
      { planet: 'Surya' as GrahaName, event: 'Surya enters Kumbha (Aquarius) on Feb 13', date: 'Feb 13, 2026', impactSummary: 'Inspires humanitarian ideals, social networking, and collective team breakthroughs.' },
      { planet: 'Shukra' as GrahaName, event: 'Shukra enters exalted sign Meena (Pisces)', date: 'Feb 15, 2026', impactSummary: 'Supreme artistic genius, spiritualized romance, empathy, and refined aesthetic joy.' },
    ],
    careerWealthForecast: 'Massive gains through professional associations, digital communities, and visionary collaborative projects.',
    loveFamilyForecast: 'Exalted Venus brings poetic romantic expressions, selfless love, and harmony with your spouse.',
    healthVitalityForecast: 'Maintain good circulation in legs, calves, and ankles. Avoid prolonged sedentary sitting; take hourly stretching breaks.',
    spiritualForecast: 'Maha Shivratri: The sacred night of Shiva. Fasting, night vigil (Jagran), and Rudrabhishekam dissolve heavy past karmas.',
    dos: [
      'Observe Maha Shivratri fast with Panchamrit Abhishekam to Shiva Lingam.',
      'Collaborate on community service or open-source collective endeavors.',
      'Cultivate forgiveness and let go of past emotional resentments.',
    ],
    donts: [
      'Avoid emotional aloofness or detachment in intimate conversations.',
      'Do not scatter focus across too many simultaneous group initiatives.',
    ],
    favorableDays: 'Feb 2, 8, 13, 18, 24',
    cautionDays: 'Feb 6, 13 (Kumbha Sankranti), 21',
    remedyOfMonth: 'Perform milk and bilva leaf Abhishekam to Lord Shiva while chanting Om Namah Shivaya 108 times.',
  },
  {
    monthKey: '2026-03',
    monthName: 'March 2026',
    tagline: 'Holika Dahan Joy & Chaitra Navratri Vedic New Year',
    overallRating: 5,
    planetaryMovements: [
      { planet: 'Surya' as GrahaName, event: 'Surya enters Meena (Pisces) on Mar 14', date: 'Mar 14, 2026', impactSummary: 'Awakens spiritual intuition, overseas connections, and compassionate service.' },
      { planet: 'Budha' as GrahaName, event: 'Budha enters Meena (Neecha sign) joined by Venus', date: 'Mid-March', impactSummary: 'Neecha Bhanga Raja Yoga forms: converts analytical confusion into profound creative intuition.' },
    ],
    careerWealthForecast: 'Remarkable for creative marketing, film/media arts, international exports, and concluding fiscal year targets.',
    loveFamilyForecast: 'Holi festivities bring colorful reconciliation and cheerful family get-togethers. High romantic empathy.',
    healthVitalityForecast: 'Spring seasonal transition: Detoxify the liver with bitter herbs and light salads. Guard against seasonal allergies.',
    spiritualForecast: 'Chaitra Navratri & Vikram Samvat Hindu New Year: Invoke the Divine Mother for auspicious yearly beginnings.',
    dos: [
      'Participate in Holika Dahan bonfire prayers to burn away inner negativity.',
      'Observe Chaitra Navratri with disciplined meditation and mantra japa.',
      'Finalize annual tax and fiscal accounts before month-end.',
    ],
    donts: [
      'Avoid synthetic toxic chemical colors during Holi play.',
      'Do not sign complex ambiguous contracts without legal scrutiny during Mercury debilitation.',
    ],
    favorableDays: 'Mar 4, 10, 15, 21, 26, 31',
    cautionDays: 'Mar 8, 14 (Meena Sankranti), 24',
    remedyOfMonth: 'Offer fragrant sandalwood paste and water to Lord Vishnu and chant the Maha Mantra.',
  },
  {
    monthKey: '2026-04',
    monthName: 'April 2026',
    tagline: 'Exalted Surya in Mesha & Ram Navami Divine Radiance',
    overallRating: 5,
    planetaryMovements: [
      { planet: 'Surya' as GrahaName, event: 'Surya enters supreme exaltation sign Mesha (Aries) on Apr 14', date: 'Apr 14, 2026', impactSummary: 'The Sun at peak celestial glory: radiates courage, sovereignty, vitality, and charismatic leadership.' },
      { planet: 'Mangal' as GrahaName, event: 'Mangal in potent friendly sign boosts executive drive', date: 'All Month', impactSummary: 'Accelerates decisive competitive victories and physical strength.' },
    ],
    careerWealthForecast: 'Supreme auspiciousness for corporate inaugurations, executive appointments, competitive exams, and breakthrough ventures.',
    loveFamilyForecast: 'Vibrant enthusiasm and celebratory mood. Ram Navami and Hanuman Jayanti inspire family unity and moral righteousness.',
    healthVitalityForecast: 'Peak cellular vitality, radiant skin, and robust immunity. Balance head heat with regular water intake and cooling pranayama.',
    spiritualForecast: 'Sri Ram Navami & Hanuman Jayanti: Recite Sundarkand or Hanuman Chalisa 11 times for total removal of fears.',
    dos: [
      'Launch long-cherished flagship projects or business enterprises.',
      'Recite Hanuman Chalisa and worship Lord Rama on Ram Navami.',
      'Spend time in nature under early morning sunlight.',
    ],
    donts: [
      'Guard against fiery outbursts, ego battles, or impatience with subordinates.',
      'Do not skip meals or become dehydrated under intense working schedules.',
    ],
    favorableDays: 'Apr 2, 8, 13, 19, 24, 29',
    cautionDays: 'Apr 6, 14 (Mesha Sankranti), 22',
    remedyOfMonth: 'Chant Gayatri Mantra 108 times at sunrise and donate copper vessels or jaggery on Tuesdays.',
  },
  {
    monthKey: '2026-05',
    monthName: 'May 2026',
    tagline: 'Akshaya Tritiya Eternal Gold & Guru Ingress into Exalted Karka',
    overallRating: 5,
    planetaryMovements: [
      { planet: 'Guru' as GrahaName, event: 'Guru enters supreme exaltation sign Karka (Cancer) forming Hamsa Yoga', date: 'Late May 2026', impactSummary: 'Monumental astrological shift: Divine Jupiter exalted brings spiritual illumination, wealth, and ethical prosperity.' },
      { planet: 'Surya' as GrahaName, event: 'Surya enters Vrishabha (Taurus) on May 15', date: 'May 15, 2026', impactSummary: 'Stabilizes wealth, speech, financial assets, and domestic acquisitions.' },
    ],
    careerWealthForecast: 'Akshaya Tritiya ensures that all investments, gold purchases, and business foundations made now yield unending prosperity.',
    loveFamilyForecast: 'Blissful domestic peace. Exalted Jupiter blesses family expansion, child conception, and sacred marriage ceremonies.',
    healthVitalityForecast: 'Robust digestion and emotional tranquility. Nurture the throat and thyroid with vocal chanting and hydration.',
    spiritualForecast: 'Akshaya Tritiya & Ganga Saptami: Sacred charity, river baths, and Vishnu Puja generate inexhaustible spiritual merit.',
    dos: [
      'Invest in auspicious gold, silver, or foundational assets on Akshaya Tritiya.',
      'Perform charitable feeding (Anna Daan) to underprivileged families.',
      'Seek Guru mantra and deepen scriptural learning under exalted Jupiter.',
    ],
    donts: [
      'Avoid hoarding wealth without sharing in charitable causes.',
      'Do not engage in stubborn, dogmatic arguments in domestic life.',
    ],
    favorableDays: 'May 3, 9, 14, 20, 25, 30',
    cautionDays: 'May 7, 15 (Vrishabha Sankranti), 23',
    remedyOfMonth: 'Donate yellow sweets and brass utensils to learned brahmins or temples on Thursdays.',
  },
  {
    monthKey: '2026-06',
    monthName: 'June 2026',
    tagline: 'Exalted Jupiter Hamsa Yoga & Nirjala Ekadashi Austerity',
    overallRating: 5,
    planetaryMovements: [
      { planet: 'Guru' as GrahaName, event: 'Guru exalted in Karka radiates divine protection to 5th, 7th & 9th houses', date: 'All Month', impactSummary: 'Bestows supreme grace, higher wisdom, ethical guidance, and auspicious fortune.' },
      { planet: 'Surya' as GrahaName, event: 'Surya enters Mithuna (Gemini) on Jun 15', date: 'Jun 15, 2026', impactSummary: 'Spurs intellectual curiosity, journalism, sibling bonding, and versatile trades.' },
    ],
    careerWealthForecast: 'Remarkable expansion in education, consulting, legal counsel, and banking. High returns on intellectual property and mentorship.',
    loveFamilyForecast: 'Generous family harmony, maternal blessings, and romantic commitment. Celebrations of family milestones and educational graduations.',
    healthVitalityForecast: 'Excellent emotional equilibrium and mental calmness. Stay hydrated during summer heat; drink fresh coconut water.',
    spiritualForecast: 'Nirjala Ekadashi & Ganga Dussehra: Observing Ekadashi fast without water bestows the spiritual merit of all 24 Ekadashis.',
    dos: [
      'Observe Nirjala Ekadashi fast with prayer and provide water to thirsty travelers.',
      'Enroll in advanced educational or spiritual certification programs.',
      'Honor mentors, professors, and spiritual teachers with gifts.',
    ],
    donts: [
      'Avoid intellectual arrogance or lecturing others unsolicited.',
      'Do not indulge in excessive gossip or speculative rumors at work.',
    ],
    favorableDays: 'Jun 2, 8, 13, 19, 24, 29',
    cautionDays: 'Jun 6, 15 (Mithuna Sankranti), 22',
    remedyOfMonth: 'Recite Sri Brihaspati Stotram on Thursdays and feed yellow bananas to cows.',
  },
  {
    monthKey: '2026-07',
    monthName: 'July 2026',
    tagline: 'Guru-Aditya Conjunction in Karka & Guru Purnima',
    overallRating: 5,
    planetaryMovements: [
      { planet: 'Surya' as GrahaName, event: 'Surya enters Karka joining exalted Guru (Guru-Aditya Yoga)', date: 'Jul 16, 2026', impactSummary: 'Creates a royal auspicious combination: supreme dignity, ethical fame, and spiritual leadership.' },
      { planet: 'Shukra' as GrahaName, event: 'Shukra transits Leo and Virgo', date: 'All Month', impactSummary: 'Cultivates graceful domestic presentation, arts, and hospitality.' },
    ],
    careerWealthForecast: 'Prestigious career recognition, public awards, and government commendations. High favor from superiors and executive boards.',
    loveFamilyForecast: 'Guru Purnima brings deep family reverence and heartfelt gratitude. Domestic sanctuary feels uplifting and peaceful.',
    healthVitalityForecast: 'Guard against monsoon dampness and seasonal colds. Drink warm golden milk with turmeric and black pepper before bed.',
    spiritualForecast: 'Guru Purnima: Sacred day for renewing spiritual vows, meditating on the Satguru, and studying sacred texts.',
    dos: [
      'Worship Lord Shiva and the Guru lineage on Guru Purnima.',
      'Apply for grants, patents, or executive leadership positions.',
      'Drink warm boiled water infused with tulsi and cinnamon.',
    ],
    donts: [
      'Avoid taking ethical shortcuts under competitive pressure.',
      'Do not disrespect parents or teachers in heated debates.',
    ],
    favorableDays: 'Jul 4, 10, 15, 21, 26, 30',
    cautionDays: 'Jul 8, 16 (Karka Sankranti), 25',
    remedyOfMonth: 'Offer yellow flowers and water to a Peepal tree on Thursday mornings (do not touch tree on Thursday).',
  },
  {
    monthKey: '2026-08',
    monthName: 'August 2026',
    tagline: 'Surya in Simha & Krishna Janmashtami Transcendence',
    overallRating: 5,
    planetaryMovements: [
      { planet: 'Surya' as GrahaName, event: 'Surya enters royal sign Simha on Aug 17', date: 'Aug 17, 2026', impactSummary: 'Reignites supreme self-confidence, administrative competence, and vitality.' },
      { planet: 'Guru' as GrahaName, event: 'Exalted Guru aspects vital houses with divine beneficence', date: 'All Month', impactSummary: 'Shields against obstacles, enhances speculative discernment, and blesses children.' },
    ],
    careerWealthForecast: 'Outstanding for leadership promotions, governmental bids, and institutional funding. Strategic boldness pays handsome dividends.',
    loveFamilyForecast: 'Raksha Bandhan and Janmashtami foster deep joyful domestic reunions, sibling protection, and festive devotion.',
    healthVitalityForecast: 'Vibrant metabolic fire and cardiac vitality. Practice moderate cardio and avoid spicy fried late-night feasts.',
    spiritualForecast: 'Shravana Purnima & Krishna Janmashtami: Midnight fasting and chanting Om Namo Bhagavate Vasudevaya brings profound inner joy.',
    dos: [
      'Chant Aditya Hridaya Stotra at sunrise.',
      'Celebrate Raksha Bandhan and Janmashtami with traditional joy and charity.',
      'Spearhead key organizational reforms with confident leadership.',
    ],
    donts: [
      'Avoid high-handed pride or dismissive conduct toward peers.',
      'Do not compromise sleep during late-night festival celebrations.',
    ],
    favorableDays: 'Aug 3, 9, 14, 19, 24, 29',
    cautionDays: 'Aug 7, 17 (Simha Sankranti), 26',
    remedyOfMonth: 'Offer white butter and sugar candy (Makhan-Mishri) to Lord Krishna on Janmashtami.',
  },
  {
    monthKey: '2026-09',
    monthName: 'September 2026',
    tagline: 'Solar Alignment in Kanya & Jupiter Intellectual Expansion',
    overallRating: 4,
    planetaryMovements: [
      { planet: 'Surya' as GrahaName, event: 'Surya enters Kanya (Virgo) on Sep 17', date: 'Sep 17, 2026', impactSummary: 'Analytical precision and organizational audits take center stage.' },
      { planet: 'Guru' as GrahaName, event: 'Guru continues steady transit in Karka (exalted)', date: 'All Month', impactSummary: 'Broadens networking, commerce, and emotional maturity.' },
      { planet: 'Shani' as GrahaName, event: 'Shani retrograde in Meena', date: 'All Month', impactSummary: 'Deep karmic review of subconscious commitments and emotional roots.' },
    ],
    careerWealthForecast: 'Favorable for reviewing performance metrics, renegotiating supplier contracts, and implementing structured workflow improvements.',
    loveFamilyForecast: 'Clear and gentle communication resolves prior misunderstandings. Ideal time for intellectual bonding and quiet dates.',
    healthVitalityForecast: 'Focus on digestion and gut health. Incorporate Ayurvedic triphala or warm herbal infusions.',
    spiritualForecast: 'Pitru Paksha / Shradha period in late September: Dedicate time to ancestral prayers and charitable feeding.',
    dos: [
      'Organize pending financial accounts and tax documentation.',
      'Perform Tarpan or charitable donations for ancestral blessings.',
      'Adopt a consistent morning yoga and Pranayama sequence.',
    ],
    donts: [
      'Avoid hypercritical perfectionism with colleagues or family.',
      'Do not skip balanced meals under work pressure.',
    ],
    favorableDays: 'Sep 3, 7, 12, 18, 22, 27',
    cautionDays: 'Sep 9, 15, 29 (Moon in 8th/12th axis)',
    remedyOfMonth: 'Chant Surya Gayatri at dawn and donate wheat or copper vessels on Sundays.',
  },
  {
    monthKey: '2026-10',
    monthName: 'October 2026',
    tagline: 'Sharad Navratri Divine Grace & Solar Ingress into Tula',
    overallRating: 5,
    planetaryMovements: [
      { planet: 'Surya' as GrahaName, event: 'Surya enters Tula on Oct 17', date: 'Oct 17, 2026', impactSummary: 'Demands diplomatic tact, humility, and avoiding ego frictions.' },
      { planet: 'Shukra' as GrahaName, event: 'Shukra transit in own sign Tula & Vrischika', date: 'Oct 10-31', impactSummary: 'Magnificent artistic inspiration, relationship harmony, and social charisma.' },
      { planet: 'Mangal' as GrahaName, event: 'Mangal aspects vital houses from Karka', date: 'Mid-October', impactSummary: 'Spurs emotional passion and domestic renovation drives.' },
    ],
    careerWealthForecast: 'Strategic diplomacy beats blunt force. Partnership ventures require clear legal clauses before formal signing.',
    loveFamilyForecast: 'High romantic fulfillment and social invitations during Navratri and Sharad Purnima festivities.',
    healthVitalityForecast: 'Keep kidneys and lower back balanced with adequate hydration and gentle stretching.',
    spiritualForecast: 'Sharad Navratri: Invoke Goddess Durga with daily Chandi Path or Durga Saptashati recitation.',
    dos: [
      'Celebrate Navratri with sattvic fasting and devotional music.',
      'Harmonize marital relations through thoughtful gestures and active listening.',
      'Decorate home sanctum with fresh flowers and brass lamps.',
    ],
    donts: [
      'Avoid ostentatious vanity or overspending on luxury attire.',
      'Do not engage in legal confrontations after Oct 17.',
    ],
    favorableDays: 'Oct 2, 8, 14, 19, 24, 30',
    cautionDays: 'Oct 6, 17 (Sankranti day), 28',
    remedyOfMonth: 'Recite Sri Suktam on Fridays and offer white sweets or milk to Goddess Lakshmi.',
  },
  {
    monthKey: '2026-11',
    monthName: 'November 2026',
    tagline: 'Diwali Auspicious Radiance & Deep Scorpionic Transformation',
    overallRating: 5,
    planetaryMovements: [
      { planet: 'Surya' as GrahaName, event: 'Surya enters Vrischika on Nov 16', date: 'Nov 16, 2026', impactSummary: 'Initiates profound psychological insight, research, and occult interest.' },
      { planet: 'Budha' as GrahaName, event: 'Budha retrograde cycle in Vrischika', date: 'Nov 20-30', impactSummary: 'Urges double-checking email communications and financial transfers.' },
      { planet: 'Guru' as GrahaName, event: 'Jupiter aspects 5th/9th houses with divine trine', date: 'All Month', impactSummary: 'Blessings for speculative intelligence, children, and spiritual teachers.' },
    ],
    careerWealthForecast: 'Exceptional for financial audits, debt settlements, strategic asset acquisitions, and festive Diwali sales.',
    loveFamilyForecast: 'Deep emotional intimacy and soul connections. Meaningful family reunions during Diwali and Bhai Dooj.',
    healthVitalityForecast: 'Protect reproductive and excretory wellness. Practice warming Ayurvedic oil massages (Abhyanga).',
    spiritualForecast: 'Diwali Deepavali Lakshmi Puja: Auspicious Maharatri for wealth invocation and inner illumination.',
    dos: [
      'Perform elaborate Lakshmi-Ganesh Puja during Pradosh Kaal on Diwali.',
      'Clear old debts and settle financial obligations honorably.',
      'Back up digital databases and verify bank statements.',
    ],
    donts: [
      'Avoid making major hasty electronic purchases during Mercury retrograde.',
      'Do not hold onto old family resentments during festive reunions.',
    ],
    favorableDays: 'Nov 4, 9, 13, 18, 23, 28',
    cautionDays: 'Nov 7, 21, 26',
    remedyOfMonth: 'Light 11 sesame oil lamps outside the main entrance and chant Om Shreem Mahalakshmiyei Namah.',
  },
  {
    monthKey: '2026-12',
    monthName: 'December 2026',
    tagline: 'Jupiterian Wisdom in Dhanu & Year-End Karmic Audit',
    overallRating: 4,
    planetaryMovements: [
      { planet: 'Surya' as GrahaName, event: 'Surya enters Dhanu on Dec 16', date: 'Dec 16, 2026', impactSummary: 'Awakens higher philosophical studies, long-distance travels, and dharmic integrity.' },
      { planet: 'Shani' as GrahaName, event: 'Shani direct motion in Pisces gathers speed', date: 'Late Dec', impactSummary: 'Brings tangible structural clarity to previously delayed undertakings.' },
    ],
    careerWealthForecast: 'Consolidate year-end accomplishments. Ideal for international business outreach and strategic 2027 goal setting.',
    loveFamilyForecast: 'Honest, uplifting conversations. Shared holiday excursions strengthen companionship.',
    healthVitalityForecast: 'Guard against winter chills and joint stiffness with warm spiced herbal teas (ginger, cinnamon, tulsi).',
    spiritualForecast: 'Gita Jayanti and Mokshada Ekadashi: Ideal time for studying Bhagavad Gita Chapter 12 and 15.',
    dos: [
      'Set dharmic long-range goals for the coming calendar year.',
      'Support educational charities or sponsor children’s schooling.',
      'Engage in scriptural reading and deep contemplation.',
    ],
    donts: [
      'Avoid excessive overindulgence at celebratory holiday banquets.',
      'Do not neglect regular morning spiritual practice despite cold weather.',
    ],
    favorableDays: 'Dec 3, 8, 14, 19, 25, 30',
    cautionDays: 'Dec 11, 16 (Dhanu Sankranti), 27',
    remedyOfMonth: 'Donate warm woolen blankets to the homeless on a chilly Saturday in honor of Shani and Surya.',
  },

  // ==========================================
  // YEAR 2027 (FULL 12 MONTHS TILL END OF 2027)
  // ==========================================
  {
    monthKey: '2027-01',
    monthName: 'January 2027',
    tagline: 'Makara Sankranti / Uttarayan Divine Solar Shift',
    overallRating: 5,
    planetaryMovements: [
      { planet: 'Surya' as GrahaName, event: 'Surya enters Makara (Capricorn) on Jan 14', date: 'Jan 14, 2027', impactSummary: 'Uttarayan begins: The Northern celestial path brings vitality, light, and breakthrough vigor.' },
      { planet: 'Mangal' as GrahaName, event: 'Mangal in potent angular transit', date: 'All Month', impactSummary: 'Drives ambitious enterprise execution and physical stamina.' },
    ],
    careerWealthForecast: 'Powerful momentum for new business ventures, corporate promotions, and decisive leadership actions.',
    loveFamilyForecast: 'Stable, grounded relationships. Mutual respect and collaborative life planning flourish.',
    healthVitalityForecast: 'High stamina and physical resilience. Excellent for initiating new athletic or fitness regimes.',
    spiritualForecast: 'Makara Sankranti sacred holy dip and Surya Gayatri sadhana for life-force renewal.',
    dos: [
      'Eat sesame and jaggery (Til-Gud) and donate khichdi on Makara Sankranti.',
      'Launch disciplined enterprise initiatives with clear operational milestones.',
      'Establish a consistent wake-up routine at Brahma Muhurta.',
    ],
    donts: [
      'Avoid harsh, demanding speech with junior associates or apprentices.',
      'Do not let relentless career ambitions displace family evening dinners.',
    ],
    favorableDays: 'Jan 4, 10, 15, 20, 26, 31',
    cautionDays: 'Jan 8, 14 (Sankranti day), 23',
    remedyOfMonth: 'Chant Aditya Hridaya Stotra on Sundays facing East at sunrise.',
  },
  {
    monthKey: '2027-02',
    monthName: 'February 2027',
    tagline: 'Mahashivratri Auspicious Awakening & Air Sign Harmonies',
    overallRating: 4,
    planetaryMovements: [
      { planet: 'Surya' as GrahaName, event: 'Surya enters Kumbha (Aquarius) on Feb 13', date: 'Feb 13, 2027', impactSummary: 'Encourages social reforms, collaborative groups, and human welfare endeavors.' },
      { planet: 'Shukra' as GrahaName, event: 'Shukra reaches exaltation degree in Meena', date: 'Mid-February', impactSummary: 'Supreme artistic genius, unconditional love, and spiritual compassion peak.' },
    ],
    careerWealthForecast: 'Massive gains through collective networks, tech communities, and non-profit or humanitarian endeavors.',
    loveFamilyForecast: 'Exalted Venus brings transcendental romantic expressions and deep soulmate empathy.',
    healthVitalityForecast: 'Pay attention to blood circulation and calves/ankles. Practice gentle calf stretches and hydration.',
    spiritualForecast: 'Maha Shivratri: The supreme night of Shiva consciousness for destroying negative karmas and attaining peace.',
    dos: [
      'Observe Maha Shivratri fast with Panchamrit Abhishekam to Shiva Lingam.',
      'Collaborate with community groups on altruistic social causes.',
      'Foster forgiveness and let go of past relationship grievances.',
    ],
    donts: [
      'Avoid cold cynicism or emotional aloofness in close relationships.',
      'Do not scatter your focus across too many simultaneous collaborative projects.',
    ],
    favorableDays: 'Feb 3, 9, 14, 19, 24',
    cautionDays: 'Feb 7, 13 (Sankranti), 21',
    remedyOfMonth: 'Perform Rudrabhishekam with milk and bilva leaves on Maha Shivratri while chanting Om Namah Shivaya.',
  },
  {
    monthKey: '2027-03',
    monthName: 'March 2027',
    tagline: 'Chaitra Navratri & Holi Celebrations of Renewal',
    overallRating: 5,
    planetaryMovements: [
      { planet: 'Surya' as GrahaName, event: 'Surya enters Meena on Mar 15', date: 'Mar 15, 2027', impactSummary: 'Inspires deep spiritual introspection, charitable generosity, and overseas connections.' },
      { planet: 'Guru' as GrahaName, event: 'Guru transit across Karka/Simha threshold', date: 'All Month', impactSummary: 'Bridges emotional wisdom with executive dignity and moral authority.' },
    ],
    careerWealthForecast: 'Favorable for creative endeavors, closing annual financial books, and expanding into foreign client accounts.',
    loveFamilyForecast: 'Holi celebration of colors creates heart-opening reunions. Warm, affectionate harmony in married life.',
    healthVitalityForecast: 'Support lymphatic and liver detoxification through bitter spring greens and adequate water intake.',
    spiritualForecast: 'Chaitra Navratri & Hindu New Year (Vikram Samvat): Auspicious period to invoke Divine Mother Durga.',
    dos: [
      'Participate in Holika Dahan to symbolically burn past grievances.',
      'Observe Chaitra Navratri with daily mantra sadhana and vegetarian purity.',
      'Settle pending debts and reconcile financial books before the new fiscal cycle.',
    ],
    donts: [
      'Avoid overexerting yourself in chaotic festival crowds.',
      'Do not make impulsive speculative stock trades during Sankranti days.',
    ],
    favorableDays: 'Mar 3, 8, 14, 19, 25, 30',
    cautionDays: 'Mar 7, 15 (Meena Sankranti), 23',
    remedyOfMonth: 'Offer yellow flowers and chant Vishnu Sahasranama on Ekadashi.',
  },
  {
    monthKey: '2027-04',
    monthName: 'April 2027',
    tagline: 'Surya Exaltation in Mesha & Sri Ram Navami Grace',
    overallRating: 5,
    planetaryMovements: [
      { planet: 'Surya' as GrahaName, event: 'Surya enters exaltation sign Mesha (Aries) on Apr 14', date: 'Apr 14, 2027', impactSummary: 'Peak solar authority, confidence, physical vitality, and triumph over rivals.' },
      { planet: 'Mangal' as GrahaName, event: 'Mangal in friendly transit boosts stamina', date: 'All Month', impactSummary: 'Sharpened athletic stamina, competitive edge, and decisive strategy.' },
    ],
    careerWealthForecast: 'Prime window for major promotions, governmental tender approvals, executive leadership, and groundbreaking enterprise launches.',
    loveFamilyForecast: 'Vibrant enthusiasm and joyful family gatherings. Ram Navami and Hanuman Jayanti bring righteous moral strength.',
    healthVitalityForecast: 'Peak cellular energy and robust immunity. Balance head heat with regular water intake and cooling pranayama.',
    spiritualForecast: 'Sri Ram Navami and Hanuman Jayanti: Chanting Ram Naam and Hanuman Chalisa protects against all adversities.',
    dos: [
      'Launch long-awaited enterprise milestones under exalted solar rays.',
      'Recite Hanuman Chalisa and worship Lord Rama on Ram Navami.',
      'Take morning walks in early sunshine to charge your solar plexus chakra.',
    ],
    donts: [
      'Avoid authoritarian hubris or hot-headed disputes with peers.',
      'Do not neglect domestic peace under high-intensity work pressure.',
    ],
    favorableDays: 'Apr 2, 7, 12, 18, 23, 28',
    cautionDays: 'Apr 6, 14 (Mesha Sankranti), 22',
    remedyOfMonth: 'Chant the Gayatri Mantra 108 times at sunrise and donate copper vessels or jaggery on Tuesdays.',
  },
  {
    monthKey: '2027-05',
    monthName: 'May 2027',
    tagline: 'Akshaya Tritiya Eternal Gold & Guru Ingress into Simha',
    overallRating: 5,
    planetaryMovements: [
      { planet: 'Guru' as GrahaName, event: 'Guru enters royal sign Simha (Leo)', date: 'Late May 2027', impactSummary: 'Magnificent transit: Jupiter in Leo fosters regal leadership, creative brilliance, and dharmic governance.' },
      { planet: 'Surya' as GrahaName, event: 'Surya enters Vrishabha (Taurus) on May 15', date: 'May 15, 2027', impactSummary: 'Stabilizes material assets, banking liquidity, and high culinary refinement.' },
    ],
    careerWealthForecast: 'Akshaya Tritiya brings unyielding prosperity for real estate purchases, gold accumulation, and long-term business partnerships.',
    loveFamilyForecast: 'Generous warmth, festive family dining, and harmonious partnerships. Marital bonds deepen with trust.',
    healthVitalityForecast: 'Strong physical constitution. Guard throat and vocal cords with warm herbal gargles if speaking extensively.',
    spiritualForecast: 'Akshaya Tritiya: Inexhaustible spiritual merit earned through feeding the hungry, gifting sacred books, and Vishnu worship.',
    dos: [
      'Purchase auspicious gold, silver, or foundational assets on Akshaya Tritiya.',
      'Perform charitable feeding (Anna Daan) to underprivileged families.',
      'Seek Guru mantra and deepen scriptural learning under Jupiter in Leo.',
    ],
    donts: [
      'Avoid hoarding wealth without sharing in charitable causes.',
      'Do not engage in stubborn, dogmatic arguments in domestic life.',
    ],
    favorableDays: 'May 4, 10, 15, 21, 26, 31',
    cautionDays: 'May 8, 15 (Vrishabha Sankranti), 24',
    remedyOfMonth: 'Donate yellow sweets and brass utensils to learned elders or spiritual institutions on Thursdays.',
  },
  {
    monthKey: '2027-06',
    monthName: 'June 2027',
    tagline: 'Jupiter in Simha Regal Dharma & Nirjala Ekadashi',
    overallRating: 5,
    planetaryMovements: [
      { planet: 'Guru' as GrahaName, event: 'Guru transits Simha with royal wisdom', date: 'All Month', impactSummary: 'Expands creative intelligence, executive standing, and spiritual mentor status.' },
      { planet: 'Surya' as GrahaName, event: 'Surya enters Mithuna on Jun 15', date: 'Jun 15, 2027', impactSummary: 'Encourages versatility, digital communications, short trips, and trade agreements.' },
    ],
    careerWealthForecast: 'High commercial expansion through media, communications, publishing, and leadership consulting.',
    loveFamilyForecast: 'Lively, intellectually stimulating conversations. Celebrations of educational achievements and children’s milestones.',
    healthVitalityForecast: 'Keep body cool and well-hydrated during peak summer heat. Drink fresh melon juices and tender coconut water.',
    spiritualForecast: 'Nirjala Ekadashi & Ganga Dussehra: Supreme fasting days that burn negative karmic residues and elevate consciousness.',
    dos: [
      'Observe Nirjala Ekadashi with prayer and provide cold drinking water to travelers.',
      'Spearhead innovative public campaigns and collaborative partnerships.',
      'Express heartfelt gratitude to your father and teachers.',
    ],
    donts: [
      'Avoid superficial scatter of focus across too many simultaneous tasks.',
      'Do not dismiss traditional counsel from seasoned elders.',
    ],
    favorableDays: 'Jun 3, 9, 14, 20, 25, 30',
    cautionDays: 'Jun 7, 15 (Mithuna Sankranti), 23',
    remedyOfMonth: 'Chant Om Namo Bhagavate Vasudevaya 108 times and donate seasonal fruits to children.',
  },
  {
    monthKey: '2027-07',
    monthName: 'July 2027',
    tagline: 'Guru Purnima Sacred Light & Shravana Maas Devotion',
    overallRating: 5,
    planetaryMovements: [
      { planet: 'Surya' as GrahaName, event: 'Surya enters Karka on Jul 16 (Karka Sankranti)', date: 'Jul 16, 2027', impactSummary: 'Activates emotional intelligence, maternal care, and domestic tranquility.' },
      { planet: 'Guru' as GrahaName, event: 'Guru in Simha aspects 5th, 7th, and 9th houses', date: 'All Month', impactSummary: 'Supreme dharmic shield over relationships, progeny, and fortune.' },
    ],
    careerWealthForecast: 'Favorable for long-term domestic investments, real estate acquisitions, and creative educational programs.',
    loveFamilyForecast: 'Guru Purnima and Shravana bring deep family devotion. Marital intimacy thrives on mutual care and empathy.',
    healthVitalityForecast: 'Guard against water-borne monsoon illnesses. Consume light, freshly cooked sattvic meals with digestive ginger.',
    spiritualForecast: 'Guru Purnima & Shravana Somwar: Auspicious Monday fasts dedicated to Lord Shiva for fulfillment of heart’s wishes.',
    dos: [
      'Offer reverent homage and dakshina to your Guru or mentors on Guru Purnima.',
      'Observe Shravana Somwar fast with Jalabhishekam to Lord Shiva.',
      'Strengthen domestic bonds through shared devotional prayers at home.',
    ],
    donts: [
      'Avoid non-vegetarian or stale food during sacred Shravan month.',
      'Do not react defensively to domestic feedback from your spouse.',
    ],
    favorableDays: 'Jul 2, 8, 13, 19, 24, 29',
    cautionDays: 'Jul 6, 16 (Karka Sankranti), 25',
    remedyOfMonth: 'Perform sacred Jalabhishekam with Gangajal and bilva patra on Mondays while chanting the Maha Mrityunjaya Mantra.',
  },
  {
    monthKey: '2027-08',
    monthName: 'August 2027',
    tagline: 'Surya & Guru Conjunction in Simha & Krishna Janmashtami',
    overallRating: 5,
    planetaryMovements: [
      { planet: 'Surya' as GrahaName, event: 'Surya enters own sign Simha joining Guru (Guru-Aditya Yoga in Leo)', date: 'Aug 17, 2027', impactSummary: 'Extraordinary royal conjunction in royal sign: peaks authority, ethical wisdom, and fame.' },
      { planet: 'Mangal' as GrahaName, event: 'Mangal transit reinforces competitive victories', date: 'All Month', impactSummary: 'Decisive tactical execution, high physical energy, and courageous leadership.' },
    ],
    careerWealthForecast: 'One of the most powerful career and enterprise windows of 2027. Major promotions, executive wins, and lucrative contracts.',
    loveFamilyForecast: 'Raksha Bandhan and Janmashtami foster joyful domestic reunions and sibling devotion. High mutual respect in marriage.',
    healthVitalityForecast: 'Radiant vitality and high metabolic energy. Balance Pitta by avoiding overly fiery condiments.',
    spiritualForecast: 'Krishna Janmashtami: Deep midnight meditation and chanting Hare Krishna Maha Mantra yields profound inner bliss.',
    dos: [
      'Take bold, decisive leadership initiatives in your career or enterprise.',
      'Celebrate Rakhi and Janmashtami with sacred family rituals and charity.',
      'Worship Lord Surya and Lord Vishnu at dawn for continuous prosperity.',
    ],
    donts: [
      'Avoid tyrannical ego clashes or disrespect toward colleagues.',
      'Do not allow sudden pride to overshadow humbleness and gratitude.',
    ],
    favorableDays: 'Aug 4, 10, 15, 20, 26, 31',
    cautionDays: 'Aug 8, 17 (Simha Sankranti), 27',
    remedyOfMonth: 'Offer fresh water with saffron and red sandalwood to Lord Surya at sunrise every Sunday.',
  },
  {
    monthKey: '2027-09',
    monthName: 'September 2027',
    tagline: 'Pitru Paksha Tarpan & Exalted Budha in Kanya',
    overallRating: 4,
    planetaryMovements: [
      { planet: 'Budha' as GrahaName, event: 'Budha in exalted sign Kanya forming Bhadra Yoga', date: 'Sep 10-30', impactSummary: 'Unsurpassed commercial acumen, data analytics mastery, and precision communication.' },
      { planet: 'Surya' as GrahaName, event: 'Surya enters Kanya on Sep 17', date: 'Sep 17, 2027', impactSummary: 'Shifts focus toward service, health audits, accounting discipline, and detail execution.' },
    ],
    careerWealthForecast: 'Superb for financial audits, contract revisions, software architectures, and analytical research projects.',
    loveFamilyForecast: 'Quiet, thoughtful family harmony. Honoring ancestors brings subtle peace and removes lingering domestic friction.',
    healthVitalityForecast: 'Focus on digestion and gut health. Incorporate Ayurvedic triphala or warm herbal infusions.',
    spiritualForecast: 'Pitru Paksha: Dedicate 16 days to Tarpan, Pinda Daan, and feeding cows, crows, and underprivileged persons for Pitru Dosha relief.',
    dos: [
      'Perform Tarpan or charitable donations for ancestral blessings.',
      'Organize accounting books, tax declarations, and legal wills.',
      'Leverage exalted Mercury for data analysis, writing, and strategic study.',
    ],
    donts: [
      'Avoid hypercritical perfectionism with colleagues or family.',
      'Do not skip balanced meals under work pressure.',
    ],
    favorableDays: 'Sep 2, 7, 12, 18, 23, 28',
    cautionDays: 'Sep 6, 17 (Kanya Sankranti), 25',
    remedyOfMonth: 'Feed green grass or spinach to cows on Wednesdays and donate black sesame seeds on Saturdays.',
  },
  {
    monthKey: '2027-10',
    monthName: 'October 2027',
    tagline: 'Sharad Navratri Divine Shakti & Dussehra Victory',
    overallRating: 5,
    planetaryMovements: [
      { planet: 'Surya' as GrahaName, event: 'Surya enters Tula on Oct 17', date: 'Oct 17, 2027', impactSummary: 'Demands diplomatic tact, humility, and avoiding ego frictions.' },
      { planet: 'Shukra' as GrahaName, event: 'Shukra transit in own sign Tula & Vrischika', date: 'Oct 10-31', impactSummary: 'Magnificent artistic inspiration, relationship harmony, and social charisma.' },
    ],
    careerWealthForecast: 'Strategic diplomacy beats blunt force. Partnership ventures require clear legal clauses before formal signing.',
    loveFamilyForecast: 'High romantic fulfillment and social invitations during Navratri and Sharad Purnima festivities.',
    healthVitalityForecast: 'Keep kidneys and lower back balanced with adequate hydration and gentle stretching.',
    spiritualForecast: 'Sharad Navratri: Invoke Goddess Durga with daily Chandi Path or Durga Saptashati recitation.',
    dos: [
      'Celebrate Navratri with sattvic fasting and devotional music.',
      'Harmonize marital relations through thoughtful gestures and active listening.',
      'Decorate home sanctum with fresh flowers and brass lamps.',
    ],
    donts: [
      'Avoid ostentatious vanity or overspending on luxury attire.',
      'Do not engage in legal confrontations after Oct 17.',
    ],
    favorableDays: 'Oct 3, 9, 14, 20, 25, 30',
    cautionDays: 'Oct 7, 17 (Tula Sankranti), 28',
    remedyOfMonth: 'Recite Sri Suktam on Fridays and offer white sweets or milk to Goddess Lakshmi.',
  },
  {
    monthKey: '2027-11',
    monthName: 'November 2027',
    tagline: 'Diwali Deepavali Prosperity & Dev Deepawali Grace',
    overallRating: 5,
    planetaryMovements: [
      { planet: 'Surya' as GrahaName, event: 'Surya enters Vrischika on Nov 16', date: 'Nov 16, 2027', impactSummary: 'Initiates profound psychological insight, research, and occult interest.' },
      { planet: 'Guru' as GrahaName, event: 'Guru in Simha casts trine aspects on vital houses', date: 'All Month', impactSummary: 'Divine protection over speculative ventures, education, and children.' },
    ],
    careerWealthForecast: 'Exceptional for financial audits, debt settlements, strategic asset acquisitions, and festive Diwali sales.',
    loveFamilyForecast: 'Deep emotional intimacy and soul connections. Meaningful family reunions during Diwali and Bhai Dooj.',
    healthVitalityForecast: 'Protect reproductive and excretory wellness. Practice warming Ayurvedic oil massages (Abhyanga).',
    spiritualForecast: 'Diwali Deepavali Lakshmi Puja: Auspicious Maharatri for wealth invocation and inner illumination.',
    dos: [
      'Perform elaborate Lakshmi-Ganesh Puja during Pradosh Kaal on Diwali.',
      'Clear old debts and settle financial obligations honorably.',
      'Back up digital databases and verify bank statements.',
    ],
    donts: [
      'Avoid making major hasty electronic purchases without verification.',
      'Do not hold onto old family resentments during festive reunions.',
    ],
    favorableDays: 'Nov 4, 9, 13, 18, 23, 28',
    cautionDays: 'Nov 7, 16 (Vrischika Sankranti), 26',
    remedyOfMonth: 'Light 11 sesame oil lamps outside the main entrance and chant Om Shreem Mahalakshmiyei Namah.',
  },
  {
    monthKey: '2027-12',
    monthName: 'December 2027',
    tagline: 'Gita Jayanti Wisdom & 2027 Year-End Dharmic Completion',
    overallRating: 5,
    planetaryMovements: [
      { planet: 'Surya' as GrahaName, event: 'Surya enters Dhanu on Dec 16', date: 'Dec 16, 2027', impactSummary: 'Awakens higher philosophical studies, long-distance travels, and dharmic integrity.' },
      { planet: 'Shani' as GrahaName, event: 'Shani steady direct motion in Pisces brings karmic closure', date: 'All Month', impactSummary: 'Consolidates two years of karmic maturity into lasting peace and stability.' },
    ],
    careerWealthForecast: 'Grand culmination of multi-year career ambitions. Favorable for international business, legacy planning, and long-range investments.',
    loveFamilyForecast: 'Deep contentment, philosophical harmony, and heartfelt holiday gatherings with family and children.',
    healthVitalityForecast: 'Guard against winter chills with warm spiced herbal teas (ginger, cinnamon, tulsi). Practice regular joint mobility exercises.',
    spiritualForecast: 'Gita Jayanti and Mokshada Ekadashi: Ideal time for studying Bhagavad Gita Chapter 12 and 15.',
    dos: [
      'Express profound gratitude for personal and spiritual growth across 2025-2027.',
      'Donate warm woolen blankets and food to the needy on chilly Saturdays.',
      'Engage in scriptural reading, meditation, and quiet contemplation.',
    ],
    donts: [
      'Avoid excessive overindulgence at celebratory holiday banquets.',
      'Do not neglect regular morning spiritual practice despite cold weather.',
    ],
    favorableDays: 'Dec 3, 8, 14, 19, 25, 30',
    cautionDays: 'Dec 11, 16 (Dhanu Sankranti), 27',
    remedyOfMonth: 'Chant Vishnu Sahasranama on Thursdays and feed birds with soaked grains.',
  },
];
